### ISSUE TITLE
blcokParse.py: AttributeError

### ISSUE THREAD

**Issue by gang237** [beliveau-lab/OligoMiner#10]
Hello, Prof. Beliveau, 
I have met a problem when running blockParse.py file, and it seems that something is wrong with the script file, because I also met this error when using the example fasta file downloaded from the website. 

This is the error information: 
Traceback (most recent call last):
  File "blockParse.py", line 993, in <module>
    main()
  File "blockParse.py", line 981, in main
    exec ('nn_table = mt.%s' % args.nn_table)
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'DNA_NN3'

It would be very nice of you if you can help me with this problem!
Thank you so much!

**Comment by brianbeliveau** [comment]
Hello,

We have seen this error before, and in the past it was related to issues
with the Biopython install. Can you please verify you can use the
MeltingTemp module in your Python environment as in these examples:
https://biopython.org/DIST/docs/api/Bio.SeqUtils.MeltingTemp-module.html ?



------------------------------------------------
Brian J. Beliveau, Ph.D.
Assistant Professor of Genome Sciences
University of Washington
He/him/his
+1 978-390-1933 | beliveau.io

**Comment by gang237** [comment]
Hello, Prof. Beliveau,
I re-installed my biopython-1.76, and it works now!

Thank you so much!

**Comment by gang237** [comment]
Dear Professor Beliveau,

my name is Gang Wu. I have successfully run the blockparse script and got
the fasta output file after I re-installed biopython. Thank you so much!

While I have met with another problem, I can not open the webiste for
downloading nupack3.0.4. Do you have an alternative website for this?

Best wishes!

Brian J. Beliveau <notifications@github.com> 于2020年6月10日周三 上午12:33写道：

> Hello,
>
> We have seen this error before, and in the past it was related to issues
> with the Biopython install. Can you please verify you can use the
> MeltingTemp module in your Python environment as in these examples:
> https://biopython.org/DIST/docs/api/Bio.SeqUtils.MeltingTemp-module.html ?
>
>
>
> ------------------------------------------------
> Brian J. Beliveau, Ph.D.
> Assistant Professor of Genome Sciences
> University of Washington
> He/him/his
> +1 978-390-1933 | beliveau.io
>
>

**Comment by gang237** [comment]
Dear Professor Beliveau,

thank you so much! But I could not open this link. I am now in China, and I
think there might be some kind of restrictions to foreign requests due to
political reasons.

I will try to find some other websites.

Thank you so much for your help! And hope everything goes well in U.S.A.
God bless.

Best regards!

Brian J. Beliveau <notifications@github.com> 于2020年6月10日周三 下午9:48写道：

> Try this. You will need to register:
> http://www.nupack.org/downloads/register
> ------------------------------------------------
> Brian J. Beliveau, Ph.D.
> Assistant Professor of Genome Sciences
> University of Washington
> He/him/his
> +1 978-390-1933 | beliveau.io
>
>

**Comment by brianbeliveau** [comment]
Ah, you will need to contact the NUPACK developers directly in that case.

For what it's worth, we do not routinely run structureCheck as part of our
probe design pipeline, as it is computationally expensive and most probes
do not have significant secondary structure potential under FISH conditions.

------------------------------------------------
Brian J. Beliveau, Ph.D.
Assistant Professor of Genome Sciences
University of Washington
He/him/his
+1 978-390-1933 | beliveau.io

**Comment by gang237** [comment]
Dear Professor Beliveau,

thank you for your suggestions. I will try to contact  the developers.

 Best wishes!

Brian J. Beliveau <notifications@github.com> 于2020年6月11日周四 下午10:11写道：

> Ah, you will need to contact the NUPACK developers directly in that case.
>
> For what it's worth, we do not routinely run structureCheck as part of our
> probe design pipeline, as it is computationally expensive and most probes
> do not have significant secondary structure potential under FISH
> conditions.
>
> ------------------------------------------------
> Brian J. Beliveau, Ph.D.
> Assistant Professor of Genome Sciences
> University of Washington
> He/him/his
> +1 978-390-1933 | beliveau.io
>
>
