### ISSUE TITLE
Hidden readline not remove in fasta header

### ISSUE THREAD

**Issue by pawlowac** [beliveau-lab/OligoMiner#12]
Pretty self explanatory. Seems you need chrom = chrom.strip() to prevent readlines from messing with the fastq file. Bowtie2 handles it well, but any other parsing of the fastq file throws an error since probe position is on a new line.

Right now producing:

```
@NZ_CP00
:54-94
TAAATTGAAGAGTTTGATCATGGCTCAGATTGAACGCTGGC
+
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

And not:
```
@NZ_CP00:54-94
TAAATTGAAGAGTTTGATCATGGCTCAGATTGAACGCTGGC
+
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by conorcamplisson** [comment]
Hi Andrew, 

Thanks for reaching out about this!

I am trying to reproduce this issue locally; would you kindly provide: 

* a small fasta file that results in this fastq output when run through blockParse.py
* the output of `python --version` command
* your operating system

I have also started an [issue_12_dev](https://github.com/beliveau-lab/OligoMiner/tree/issue_12_dev) branch and attempted to implement the change you suggested. To test this change on your end:

```
$ git pull
$ git checkout issue_12_dev
```

and then you should be able to run the modified blockParse.py and see if it resolves the issue on your files.

Once I'm able to reproduce the issue and test a solution, I'll go ahead and merge the changes. Thanks again!

Best, 

Conor Camplisson
