### ISSUE TITLE
Python 3 support?

### ISSUE THREAD

**Issue by rubyFeedback** [beliveau-lab/OligoMiner#15]
Hey there,

Does OligoMiner work with python3 too? If so could the main README also mention this perhaps?

Background: with new python3 releases coming about, I think the number of python2 uses may
slowly shrink, and I am wondering about using software that may be "stuck" on python2. It would
be quite helpful if we could know beforehand about the support possibilities for different python
versions, to lessen frustration to those that may only use python 3.x these days (as opposed to
those who use only python 2.x, or those who actually use both versions fine).

**Comment by brianbeliveau** [comment]
Hello, OligoMiner does not work with Python 3 and as of now there are no imminent plans to change this. We recommend making a dedicated conda env with Python 2.7.x as described in the README. You can also access a web-based, dockerized version of OligoMiner at http://oligominerapp.org/home
