### ISSUE TITLE
How to obtain gene names after aligning with bowtie2 and cleaning?

### ISSUE THREAD

**Issue by charlesgwellem** [beliveau-lab/OligoMiner#16]
Hi. Thanks a lot for your helpful tool. I have followed your protocol and I have aligned sequences using bowtie2 and cleaned the ensuing SAM files to output the BED files. Is there a way to obtain gene names from these BED files? I want to obtain the gene names and the actual sequences.

Thanks in advance.

**Comment by brianbeliveau** [comment]
Hello. You can do coordinate math on the BED files to out which probes intersect with which genes, assuming you have gene annotation information in BED format. We would recommend using bedtools for this https://bedtools.readthedocs.io/en/latest/content/tools/intersect.html.

You can also find pre-computed probe-transcritome intersects at paintshop.io
