### ISSUE TITLE
does OligoMiner work for long hybride probes

### ISSUE THREAD

**Issue by biozzq** [beliveau-lab/OligoMiner#17]
Dear all,

I was wondering that whether OligoMiner is suitable for probe hybridization application, such as 120 nt probe.

Thank you very much.

Best wishes.
Zheng zhuqing

**Comment by brianbeliveau** [comment]
Hi,

Theoretically you could use it for this by setting the maximum allowed Tm to be arbitrarily high. But please keep in mind that nearest neighbor thermodynamic Tm predictions for DNA do not really extend beyond duplexes of ~60 bp, so the Tm values at  120 would not be accurate.
