### ISSUE TITLE
How to obtain candidate long probes using OligoMiner?

### ISSUE THREAD

**Issue by biozzq** [beliveau-lab/OligoMiner#19]
Dear @brianbeliveau 

As you said before(https://github.com/beliveau-lab/OligoMiner/issues/17), OligoMiner maynot suit for designing long DNA probes (e.g, 120 nt) although the long probe has many advantages over the short ones, such as 1) mitigation of secondary structure, 2) enhanced analytical sensitivity, and 3) greater tolerance to mismatches. In my following experiment, after synthesizing the DNA probes, we will first convert them to RNA probes by in vitro transcription. I think OligoMiner can help us to design the candidate probes and we can use some other tools to do quality control. I just paste my commands here, I want to ask you for advice. 
```
python blockParse.py -l 120 -L 120 -t 40 -T 200 -g 40 -G 60 -f ${dir}/${chr}.fa -o ${chr}
bowtie2 -x bowtie2.index -U ${chr}.fastq --no-hd -t -k 2 --local -D 20 -R 3 -N 1 -L 20 -i C,4 --score-min G,1,4 -p 4 -S ${chr}.sam
python outputClean.py -f ${chr}.sam -o ${chr}.uniq
python kmerFilter.py -f ${chr}.uniq.bed -m 18 -j 18mer.jf -k 3 -o ${chr}.flt.kmer
```

Best wishes,
Zheng zhuqing

**Comment by biozzq** [comment]
Dear all,

It would be great help if you guys will help me to confirm the application of `OligoMiner`. Thank you very much.

Best
Zheng zhuqing

**Comment by brianbeliveau** [comment]
Hi Zheng,

While FWIW I am not sure I would agree with the advantages listed for technical reasons, to answer your specific question:

1. That blockParse string should work fine
2. Our LDA models will not work with such long probes. My recommendation would be to tweak the alignment settings to be more strict in reporting and use -U / unique mode.
3. Likewise, you may have to elevate the -k you use with kmerFilter to account for the longer probes

**Comment by biozzq** [comment]
Dear @brianbeliveau 

Thank you very much. Do you mean that I should do that using following commands;
```
bowtie2 bowtie2.index -U ${chr}.fastq --no-hd -t -k 100 --very-sensitive-local -S ${chr}.sam
python outputClean.py -u -f ${chr}.sam -o ${chr}.uniq
```
Best wishes,
Zheng zhuqing
