### ISSUE TITLE
Exogenous sequences

### ISSUE THREAD

**Issue by episkadlo** [beliveau-lab/OligoMiner#9]
Hello,

I'm wondering how to deal with designing probes against exogenous sequences.

I've run into a problem (as was discussed here before in another issue) that the outputClean.py even with --zero mode on does not allow sequences generated with .fasta without chromosome:start-stop range in the header ('IndexError: list index out of range').  I've tried using some dummy ranges in my input fasta, but without much success.
Do you know of a good way around this issue?

Thanks!
Ewa

**Comment by brianbeliveau** [comment]
Hi Ewa,

I am not sure why your attempts to set the header in the .fasta is not working. You can also use the -H flag in blockParse to manually specify a header.

As you note, parsing of the header information has come up a few times. Updating the header parsing logic to be more robust is on our list of changes to work in.
